"""
Django settings for volgsysteem_au project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import logging.config
# from core.utils import get_valid_access_token
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
        'filters': {
        'ignore_maintenance_mode': {
            '()': 'volgsysteem_au.logging_filters.IgnoreMaintenanceModeFilter',
        },
    },
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'error.log'),
            'formatter': 'verbose',
            'filters': ['ignore_maintenance_mode'],
        },
        'console': {
            'level': 'ERROR',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'filters': ['ignore_maintenance_mode'],
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}

ADMINS = [('Rico', 'rico.lammers@avondjeuit.org')]

CSV_DIRECTORY = Path(BASE_DIR) # Define the directory where csv are exported
TEX_DIRECTORY = Path("tex")
EXCEL_COMPATIBLE_CSV = True
from dotenv import load_dotenv
import os

load_dotenv()
TOKEN = os.environ.get("TOKEN")
REFRESH_TOKEN = os.environ.get("REFRESH_TOKEN")
OAUTH_CLIENT_ID = os.environ.get("OAUTH_CLIENT_ID")
OAUTH_CLIENT_SECRET = os.environ.get("OAUTH_CLIENT_SECRET")

HEADERS = {
  'Content-Type': 'application/json',
  'Accept': '["application/json", "text/plain", "*/*"]',
    "Authorization": TOKEN
}

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+(0c^m2fo*_de^vuu^%i&y5zon+#)vaniy52u&)vg)%4q)p8jg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
MAINTENANCE_MODE = None
MAINTENANCE_MODE_IGNORE_SUPERUSER = False
MAINTENANCE_MODE_STATE_FILE_PATH = os.path.join(BASE_DIR, "maintenance_mode_state.txt")

ALLOWED_HOSTS = ['*']
# X_FRAME_OPTIONS = 'SAMEORIGIN'
X_FRAME_OPTIONS = 'ALLOWALL'

CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    "http://localhost:8000",
    'http://volgsysteem.avondjeuit.org',
    'https://volgsysteem.avondjeuit.org']
CORS_ALLOWED_ORIGINS = [
    'http://127.0.0.1:8000',
    "http://localhost:8000",
    'http://volgsysteem.avondjeuit.org',
    'https://volgsysteem.avondjeuit.org']
CORS_ORIGIN_WHITELIST = [
    'http://127.0.0.1:8000',
    "http://localhost:8000",
    'http://volgsysteem.avondjeuit.org',
    'https://volgsysteem.avondjeuit.org']
CORS_ALLOW_CREDENTIALS= True

LOGIN_REDIRECT_URL = "core:index"
LOGOUT_REDIRECT_URL = "core:index"

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    "debug_toolbar",
    'bootstrapform',
    'django_o365mail',
    'core',
    'survey',
    'rest_framework',
    #'kaart',
    #'django_plotly_dash.apps.DjangoPlotlyDashConfig',
    #'channels',
    'maintenance_mode',

]
PLOTLY_COMPONENTS = [
    'dash_core_components',
    'dash_html_components',
    'dash_daq',
]
DP_DASH_CONFIG = {
    "SINGLETON": False,
    "DISPLAY_MODE": "inline"
}
SITE_ID = 1 

MIDDLEWARE = [
    'maintenance_mode.middleware.MaintenanceModeMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "corsheaders.middleware.CorsMiddleware",

    'django_plotly_dash.middleware.BaseMiddleware',
    'django_plotly_dash.middleware.ExternalRedirectionMiddleware',
    
]

STATICFILES_FINDERS = [
    'django_plotly_dash.finders.DashAssetFinder',
    'django_plotly_dash.finders.DashComponentFinder',
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]


ROOT_URLCONF = 'volgsysteem_au.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS':[BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'volgsysteem_au.wsgi.application'

DATA_UPLOAD_MAX_NUMBER_FIELDS = 10240
# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    # ...
]
# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

#LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'nl'
TIME_ZONE = 'Europe/Amsterdam'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# Statische bestanden configureren
STATIC_URL = '/static/'  # Dit is de URL waar je statische bestanden zullen worden geladen

# Voor productie (na collectstatic)
STATIC_ROOT = BASE_DIR / 'staticfiles'  # De map waar statische bestanden worden verzameld

# Locaties van extra statische bestanden (specifieke mappen voor je apps)
STATICFILES_DIRS = [
    BASE_DIR / 'static',
    BASE_DIR / 'core' / 'static',  # Statische bestanden voor de 'core' app
    BASE_DIR / 'volgsysteem_au' / 'static',
]


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


#### TOEGEVOEGD 30-07-2024
EMAIL_BACKEND = 'core.backends.CustomEmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST')
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')  # Je inlog e-mailadres
DEFAULT_FROM_EMAIL =os.environ.get('DEFAULT_FROM_EMAIL') 

TENANT_ID = os.environ.get('TENANT_ID')
CLIENT_ID = os.environ.get('CLIENT_ID')
CLIENT_SECRET = os.environ.get('CLIENT_SECRET')
SCOPE = 'https://outlook.office365.com/.default'
EMAIL_HOST = 'smtp.office365.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True